# Generated by Django 5.0.1 on 2024-02-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reading Date')),
                ('pages_read', models.IntegerField(default=0)),
                ('mood', models.CharField(blank=True, choices=[('H', 'Happy'), ('S', 'Sad'), ('R', 'Relaxed'), ('E', 'Excited'), ('C', 'Curious'), ('T', 'Tired')], max_length=1)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='main_app.book')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
